# Generated by Django 5.0.6 on 2024-06-16 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='membresias',
            fields=[
                ('id_membresia', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_membresia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_User', models.CharField(max_length=200)),
                ('apellido_User', models.CharField(max_length=200)),
                ('correo_User', models.CharField(max_length=200)),
                ('password_User', models.CharField(max_length=200)),
                ('membresia_id_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapp.membresias')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_Historial', models.AutoField(primary_key=True, serialize=False)),
                ('Procesos_Historial', models.TextField()),
                ('id_user_Historial', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapp.usuarios')),
            ],
        ),
    ]
