# Generated by Django 5.0.6 on 2024-06-17 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_differencedividedhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiseccionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=255)),
                ('a_value', models.FloatField()),
                ('b_value', models.FloatField()),
                ('tol_porcentual', models.FloatField()),
                ('root', models.FloatField()),
                ('iterations', models.IntegerField()),
                ('final_error', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
