# Generated by Django 5.0.6 on 2024-06-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_biseccionhistory'),
    ]

    operations = [
    ]
