# Generated by Django 5.0.6 on 2024-06-20 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_profile_delete_biseccionhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='BiseccionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecuacion', models.CharField(max_length=255)),
                ('valor_min', models.FloatField()),
                ('valor_max', models.FloatField()),
                ('error_porcentual', models.FloatField()),
                ('raiz_aproximada', models.FloatField()),
                ('iter_count', models.IntegerField()),
                ('error_final', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
