# Generated by Django 5.0.6 on 2024-06-20 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_profile_image_biseccionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='biseccionhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
