# Generated by Django 5.0.6 on 2024-06-22 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_biseccionhistory_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biseccionhistory',
            name='error_final',
        ),
    ]
